### ISSUE TITLE
Add functional output 

### ISSUE THREAD

**Issue by fthirion89** [metagenopolis/meteor#48]
List of functional outputs that should be generated:
- sum of genes for kegg, dban and mustard (curretnly, onlt mustard)
- sum of msps for kegg, dbcan and mustard (currently, only dbcan)

Line 639 and 640 of profiler.py:
Change ["mustard"] with ["mustard", "kegg", "dbcan"]
Change ["dbcan] with ["mustard", "kegg", "dbcan"]

Probably test associated with the function execute() should be updated.

**Comment by aghozlane** [comment]
Done!
